### ISSUE TITLE
invert edges interaction

### ISSUE THREAD

**Issue by toebner** [bp-bahn-order/soro-s#12]
## Description
As a user i want to be able to interact the graph, so that clicking on an edge of the graph inverts the direction.
## Acceptance Critera
- Only edges where the source and target of the edge belong to a different train are invertable.
- The displayed graph gets displayed accordingly with all changed edges being visible.
## Notes
- only one edge should be inverted at a time
- this functionality represents changing the order in which two different trains on a specific route
### Tasks
- [x] https://github.com/bp-bahn-order/soro-s/issues/13
- [x] https://github.com/bp-bahn-order/soro-s/issues/14
- [x] https://github.com/bp-bahn-order/soro-s/issues/21
## Metadata
Documentation ID: 2
Function Points: 5
Implemented by: -
Finished in Iteration: -
Total Time: -
Velocity: -
