### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by toebner** [bp-bahn-order/soro-s#27]
### Tasks
- [x] https://github.com/bp-bahn-order/soro-s/issues/28
- [x] https://github.com/bp-bahn-order/soro-s/issues/29
- [x] https://github.com/bp-bahn-order/soro-s/issues/30
## Metadata
Documentation ID: 2
Function Points: 5
Implemented by: -
Finished in Iteration: -
Total Time: -
Velocity: -
